// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions{
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmo5c8gBNidngA1U9A9mEtGgJWmBG1jWM',
    appId: '1:335655530106:web:d280b12e97e5fb678615c3',
    messagingSenderId: '335655530106',
    projectId: 'app-parkir-e7984',
    authDomain: 'app-parkir-e7984.firebaseapp.com',
    databaseURL: 'https://app-parkir-e7984-default-rtdb.firebaseio.com',
    storageBucket: 'app-parkir-e7984.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClwFcUs8cZzplsELuimFq6pZV0qJP7Vdo',
    appId: '1:335655530106:android:cf17705c5dda499d8615c3',
    messagingSenderId: '335655530106',
    projectId: 'app-parkir-e7984',
    databaseURL: 'https://app-parkir-e7984-default-rtdb.firebaseio.com',
    storageBucket: 'app-parkir-e7984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzuHEHI4a8cQr2WmlUcsdWTaB11xfUsfE',
    appId: '1:335655530106:ios:ece8cd0a97584f6c8615c3',
    messagingSenderId: '335655530106',
    projectId: 'app-parkir-e7984',
    databaseURL: 'https://app-parkir-e7984-default-rtdb.firebaseio.com',
    storageBucket: 'app-parkir-e7984.appspot.com',
    iosBundleId: 'com.example.appParkir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzuHEHI4a8cQr2WmlUcsdWTaB11xfUsfE',
    appId: '1:335655530106:ios:7f1062cb65423d598615c3',
    messagingSenderId: '335655530106',
    projectId: 'app-parkir-e7984',
    databaseURL: 'https://app-parkir-e7984-default-rtdb.firebaseio.com',
    storageBucket: 'app-parkir-e7984.appspot.com',
    iosBundleId: 'com.example.appParkir.RunnerTests',
  );

  
}
